language: python
python:
    - "2.7"
sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel codecov
  - pip install -r requirements.txt
script: make validate
after_success:
  - codecov

deploy:
  provider: pypi
  user: edx
  password:
    secure: A2BrU6qqQHSrJ7jvxOSr1/l4HdHT5EvRWvkufMR+kdq8I8qgTlGio22Tc4OSrD5Oe7Zz7ST7q3fJFRf8Kt/gdZp7DJeeVR5gK113EvquYQUdb+wbKiBHQ3hu7JBWAjrzUQ3mDPk5DJN77dUVByYoZUmWQVMyg2fmUnQxRdertLI=
  distributions: sdist bdist_wheel
  on:
    tags: true
