language: python
python:
    - "2.7"
sudo: false

# Cache the pip directory. "cache: pip" doesn't work due to install override. See https://github.com/travis-ci/travis-ci/issues/3239.
cache:
  directories:
    - $HOME/.cache/pip
install:
  - pip install -U pip wheel
  - pip install coveralls
  - pip install -r requirements.txt
script: make validate
after_success:
  - coveralls

deploy:
  provider: pypi
  user: edx
  password:
    secure: EX4fUMQ02zaz/pC6HWITFDm0KCBgsVSWw8SWhvzxTI0J7TPQ06HVPvVZQw5oygwBYnrqlclRUJhpkUfF904awLwW9CevIm+mbOy2hDxVbCxSIP2eFhjEluIUNUc5ps9eiBmowypPJpfgtBF3/UxYnNPRxysp/0EQqw+MANe1njs=
  distributions: "sdist bdist_wheel"
  on:
    tags: true
